### ISSUE TITLE
Handle attached file(s)

### ISSUE THREAD

**Issue by scottymeyers** [coforma/co-regulations-gov#11]
Comments may not include a message at all but just an attachment. Quickly glancing at a Comments response, it looks like there may be a subsequent request to obtain the actual URL(s), but hopefully not.

Once we can get it, let's update the table to include a link to the the file(s).

**Comment by infinityplusone** [comment]
From what I could tell, it definitely looked like it is a subsequent request. But here's my thought... Rather than *making* that subsequent request, maybe the best solution is to provide a CTA for `Check for attachments`, and then people can click on that and we make the request *then*.

**Comment by scottymeyers** [comment]
No additional request required!
